### PR TITLE
The Day 19 addressable article

### PR DESCRIPTION
**Pull request by soulcutter**
This is a Work In Progress. There will be a lot of changes through to the final version, but I don't mind early feedback.

This needs to be whipped into shape by Dec 19th - there's a deadline!

### CODE REVIEW

**Comment by geraldb** [comment]
Thanks for the addressable write-up.  Looks  good / reads great so far - sorry for not being more helpful. Cheers. Prost.

**Comment by soulcutter** [comment]
I saw how many posts are already finished and wanted to show progress so ya wouldn’t worry! 😅

**Comment by soulcutter** [comment]
@geraldb I have to level with you. I am concerned about finishing this. I am going to try my darndest. If you have a bonus article written up somewhere or some other backup plan... I want to give you early enough warning that it may be needed.

I definitely am wishing I wrote this in a different order now, because as it stands it's "minutia first" and doesn't explain Address Templates, which (to me) is really the whole point of writing about this. Argh.

As I said, I will try VERY hard in this week to complete this, but I am officially a bit worried.

**Comment by geraldb** [comment]
Thanks for the update. I see your point about URI Templates. Would be great to see an example and a paragraph or such to wrap up. Otherwise your article looks / reads great great.    No worries  - you are welcome to pick a later day - any day really until Dec/24th - there's no deadline for day 19 - if you need more time.  Would love to publish your write-up. Addressable is  a fantastic hidden gem.

**Comment by geraldb** [comment]
@soulcutter  No worries - no pressure - can you please tell me if you can make it today for Day 19 by 2pm UTC (London) time?  If not no worries - I am happy to publish your write-up once its ready in any of the upcoming days (left). Last day is the 25th.  Cheers. Prost.

**Comment by geraldb** [comment]
@soulcutter    I hope you don't mind  I have added the last paraph with a uri template example and wrap-up. No worries this is not the New Yorker magazine or such.  You're write-up is a great and it is now published and live on Day 21, see <https://planetruby.github.io/gems/2020/21-addressable>.   Happy Holidays. Cheers. Prost.

**Pull request closed without merging**
