### PR TITLE
Glimmer Tetris article series

### PR DESCRIPTION
**Pull request by AMaleh**
Hi,

I added an improved version of the Glimmer Tetris article series you once asked about as days 5, 6, & 7 under the `glimmer` directory. 

The article series walks readers through building [Glimmer Tetris](https://github.com/AMaleh/glimmer-tetris) step by step using [Glimmer DSL for SWT](https://github.com/AMaleh/glimmer-dsl-swt).

Let me know if you have any questions or requests for improvement.

Godspeed,

Andy Maleh

p.s. I am using an alternate GitHub account to AndyObtiva from a different laptop.

### CODE REVIEW

**Comment by geraldb** [comment]
Great idea. Thanks for the articles. I try to see what I can do once my life as back to some kind of normal. Thanks for the patience. Cheers.

**Comment by geraldb** [comment]
Sorry for now I have no time for editing - but I have committed / added your great articles as is. Keep it up. Changes and additions always welcome. Cheers.

**Comment by geraldb** [comment]
The <https://github.com/AMaleh/glimmer-tetris> link is 404  (in the find out more sections) - do you have a canonical / working link for the tetris source?

**Comment by AndyObtiva** [comment]
My bad! It's actually https://github.com/AMaleh/glimmer_tetris

**Comment by geraldb** [comment]
Thanks for the link. No worries.

**Comment by AndyObtiva** [comment]
OK, since you haven't published yet, I am updating all links to my AndyObtiva account (from my alt account AMaleh). I finally have access to my work laptop.

The canonical project is moved to https://github.com/AndyObtiva/glimmer_tetris

I am retesting just to make sure it is working. I will confirm to you once it is ready again for publication.

**Comment by geraldb** [comment]
No worries. Thanks for the update. I will need another couple of weeks to get back to a normal schedule (live). Cheers.

**Comment by AndyObtiva** [comment]
> Thanks for the link. No worries. I try to add some links to the Glimmer Tetris articles on the start page over the next weeks. Cheers.

Hi, are there any news regarding the posting of the Tetris article? Is there a quality issue or something you’d like me to address?

Just curious since it’s been a few weeks. 

Regards,

Andy

**Comment by geraldb** [comment]
Thanks for the reminder. The Glimmer Tetris article are already merged and published, see <https://planetruby.github.io/gems/glimmer/05-glimmer-tetris-playfield> and so on.

No worries - there's no quality issue - it's great - sorry, it's just a personal issue I have a law suit going trying to get my stolen salary back after getting fired without notice and so on, see <https://github.com/bigkorupto/mammad-kabiri-uniqa>  and I am slowly rebuilding my "normal" live and trying to find some time later this fall to update the front-page and maybe some small title edits / changes.  Thanks for the patience.

**Comment by AndyObtiva** [comment]
No worries at all.

**Comment by AndyObtiva** [comment]
Hi,

I just wanted to note that the Tetris articles were not mentioned in the README, so I added headlines for them under the Glimmer series section.

You are welcome to improve the Tetris headlines in the README if you feel there is room for improvement.

Cheers,

Andy

**Comment by geraldb** [comment]
Thanks for the README update and adding the missing Glimmer Tetris series. Keep it up. Cheers. Prost.

**Pull request merged**
