### PR TITLE
Adding happy_gemfile post

### PR DESCRIPTION
**Pull request by MikeRogers0**
I've not set a date or anything yet, but this is my post for the `happy_gemfile` gem by @MainShayne233.

This is my first draft, what do you think? Do you think it needs a before & after of how it changes the Gemfile?

### CODE REVIEW

**Comment by geraldb** [comment]
Thanks for the happy_gemfile write-up. Looks great.  Yeah would be great to add a real-world example for the Gemfile  (maybe one of the "worst" examples you have seen) and than show how it looks after running happy gemfile.

**Comment by MikeRogers0** [comment]
Awesome @geraldb ! I'll get tweaking tomorrow :D

**Comment by geraldb** [comment]
I add you to the backup list on the front page - the new (better) plan I think is to publish maybe on Sundays two posts to get your write-up published in time. Thanks again.

**Comment by MikeRogers0** [comment]
@geraldb I've made a few tweaks, but I'm a lot more happy with it now :) Over to you :D

**Comment by geraldb** [comment]
Reads great. Thanks for the write-up.

**Comment by geraldb** [comment]
Thanks again for your help - your write-up is now live, see <https://planetruby.github.io/gems/2020/10-happy-gemfile>. Cheers. Prost.

**Pull request merged**
