### PR TITLE
Update Tetris URLs

### PR DESCRIPTION
**Pull request by AndyObtiva**
This is in relation to https://github.com/planetruby/gems/pull/69 : 
- Update Tetris URLs
- Small Fixes to Tetris app

### CODE REVIEW

**Comment by geraldb** [comment]
Again thanks for the update. Keep it up.

PS: If you're interested you're more than welcome to join the planetruby org here on github - than you can edit / commit anytime - let me know if interested and I send you an invite via github (joining only works via github invites).

**Comment by AMaleh** [comment]
Sure, I’d be happy to join. Thanks for the suggestion and for merging the PR.

**Comment by AndyObtiva** [comment]
Sure, I’d be happy to join. Thanks for the suggestion and for merging the PR.

**Comment by geraldb** [comment]
FYI: Invite sent. You should get an email by github or you can use the link if I remember on top of the org page that should now show up to join with your invite, see <https://github.com/planetruby>.   You can make you membership public @  <https://github.com/orgs/planetruby/people>(default is hidden / private) if you want.  Welcome. Cheers.

**Pull request merged**
