### PR TITLE
Ruby Advent Calendar 2021 Day 22 glimmer-dsl-libui

### PR DESCRIPTION
**Pull request by AndyObtiva**
Hi,

I added [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui) as Day 22 of Ruby Advent Calendar 2021.

I am not sure if you are setting up a Ruby Advent Calendar for this year (2021). If you are, would it be OK to add my gem on Day 22? If not, I would be happy to move it into the Glimmer Days instead (which I will probably add to eventually anyways).

Best regards,

Andy Maleh

### CODE REVIEW

**Comment by geraldb** [comment]
As always thanks for your contributions and great write-ups.  Keep it up.

As it looks now I have no plan for an advent calendar 2021 - however, you are welcome to start - in that case I recommend using day 1.

Another option to publish your write-up is adding another day to the glimmer series  or  as another alternative to the gem of the week series.

Sorry there's only so much I can do.   Anyways, keep it up.

**Comment by AndyObtiva** [comment]
Thanks for the feedback.

I changed it to a Glimmer day instead.

It would be nice if you could announce on rubyflow or any of the Ruby news websites.

Cheers.

Andy

**Comment by AndyObtiva** [comment]
BTW, I just noticed this page header when I navigated to the [glimmer-dsl-libui Planet Ruby webpage](https://planetruby.github.io/gems/glimmer/08-glimmer-dsl-libui.html):

```
You have been permanently banned from participating in r/ruby (because of your writing off / outside of r/ruby). I do not see your participation adding anything to this community.

-- Richard Schneeman (r/ruby Mod)

Case Studies of Code of Conduct "Cancel Culture" Out-Of-Control Power Abuse - Ruby - A Call for Tolerance On Ruby-Talk Results In Ban On Reddit Ruby
```

It scared me at first because I thought I was really permanently banned for doing something wrong.

Would you mind taking it off or changing it since it might send the wrong message to people visiting the Planet Ruby site? I don't mind the fact that you are exposing something wrong, but that specific quote might really cause a misunderstanding and scare people off. Perhaps it could be changed to a different quote or highlight from the same story?

**Comment by geraldb** [comment]
As always thanks for your write-up and contributions.    I try to post an announcement on rubyflow about your new glimmer days gem write-up.   You're more than welcome to go ahead and send an announcement / posting to ruby-talk and so on.

About the banner - sorry for scaring you - I will add the my name in brackets - not really expecting any solidarity from the community but sorry I will keep it up as a warning as long as the ban lasts (for life, that is, until death no less).

**Comment by AndyObtiva** [comment]
Thank you. 

I would prefer it if you actually announce my write-up everywhere, including Ruby-Talk, since it would be better if I am not always the one mentioning my own work (aka tooting my own horn as the expression goes). I would not mind announcing any write-ups written by you or other people in the future.

**Comment by geraldb** [comment]
As you know I get labeled as a spammer and worse so not sure I am the right messanger :-).

Anyways, big fan of your (open source) work and writing. Please, keep it up and no worries about tooting your own work - there's a difference in my opinion if you write about your free open source work and wrting or if you actually are selling something (like for pay screencasts and such).   The first is a public service and the second is an ad.   Anyways,    just thinking out loud.  Cheers. Prost.

**Comment by AndyObtiva** [comment]
Thank you. I just saw that you improved/clarified the quote at the top of the PlanetRuby gem pages. As I mentioned before, I really don't mind having wrong being exposed, so I appreciate you shining light on the shameful wrongdoing of people who have become rotten in the Ruby community (probably due to associating with or trying to impress other rotten people). 

By the way, I wanted to note that one page hasn't changed yet (the top-level index): https://planetruby.github.io/

I seriously don't mind your postings about my work at all (I don't affirm what random posers in the Ruby community think; I simply ignore them completely to avoid giving them power over me or over anyone else). I toot my own horn far too much, and would sincerely appreciate your posting as a fresh relief from that. I would truly prefer that you post about my work when possible.

Also, I truly wouldn't mind posting links about your articles or the articles of others sharing gems on Planet Ruby. Please feel free to ask me if you would like something posted. I am new to Planet Ruby, so I would hope to contribute more to it in the future.

**Comment by geraldb** [comment]
Thanks for the update and comments.  I try to fix / update the front page.

I posted an announcment about your glimmer days write-up to ruby-talk and rubyflow.  

About writing -  since the cryptopunks-gui gem is using glimmer it would make another great write-up / posting :-)        Sorry for not being much of help on the cryptopunks-gui gem - I try to get involved for sure in the next week(s)  and send along a first patch / contribution. 

As said before you are more than welcome to start this year's advent calendar  or post more write-ups or start a new series.    For now the format and kind-of contraint is that an article usually should cover a ruby gem.     All the best. Cheers. Prost.

**Comment by AndyObtiva** [comment]
Wow! Thank you!

cryptopunks-gui should get a write-up once it is more complete. I still haven't added attribute-based image generation support yet. I would give it more time before an article is written. And, do not worry about contributing a patch. No pressure. Please do so when you feel like it only.

In any case, one thing I lately thought regarding the cryptopunks-gui gem is I could transfer the repository to the cryptopunksnotdead organization on GitHub if you don't mind. It would get more exposure by cryptopunk fans that way. If that sounds good to you, I will initiate the transfer of the [cryptopunks-gui gem repository](https://github.com/AndyObtiva/cryptopunks-gui) and make you a contributor too.

Best.

**Comment by geraldb** [comment]
> In any case, one thing I lately thought regarding the cryptopunks-gui gem is I could transfer the repository to the cryptopunksnotdead organization on GitHub if you don't mind. It would get more exposure by cryptopunk fans that way. If that sounds good to you, I will initiate the transfer of the cryptopunks-gui gem repository and make you a contributor too.

For sure that's a great idea and more than welcome.  
Last time a repo got transfer (to planetruby) - that is, /books - I remember that you CANNOT transfer directly to an org - but you have to transfer to my personal account e.g.  /geraldbauer and than I can transfer it on to the org - you will get of course all right and so on.  Let me search the internets to double check.    

About the exposure - don't expect any miracles - you are pretty much the only contributor :-) -  all the other repos on crypto punk's not dead pretty much zero - but sure there is some interest in downloading and such but hard to say.

**Comment by geraldb** [comment]
Ok. here is the update via the docs at <https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository>:

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

Thus, I add you to the cryptopunksnotdead org - that is- you should get an invite via github or should see the invite on top of the org page and than you should have the proper permission to move the repo directly to the org.

**Comment by AndyObtiva** [comment]
I actually just added you as a contributor to the repository. Once you accept, I was planning to transfer the repository to you personally so that you'd move to the cryptopunksnotdead org. That way, you do not have to give me overly-permitting access controls over the entire cryptopunksnotdead organization (I do not need them... you could remove as unnecessary) since I will only be working with the cryptopunks-gui repository.

**Comment by AndyObtiva** [comment]
By the way, on a different subject, I was wondering if you could post the glimmer-dsl-libui gem write-up on ruby.libhunt.com as well via this webpage:
https://ruby.libhunt.com/resources/new

I hope you don't mind, but that is another Ruby news website I like to check out and read from time to time.

**Comment by geraldb** [comment]
Ok - I try to post to ruby.libhunt.com

About the transafer - I sent you the invite to @AndyObtiva  - you should see the email invite on the org too (if I remember)  - if you accept you should have member rights that incl. by default the rights to create new repos  - and thus the transfer should go through / work as far as I can tell. Cheers. Prost.

**Comment by AndyObtiva** [comment]
OK, I transferred the repo to you and did not accept the invitation to cryptopunksnotdead as owner. I would rather join the cryptopunksnotdead as a non-owner since I will only operate in cryptopunks-gui.

**Comment by geraldb** [comment]
Note: The invite is a "standard" member invite - it is not an owner invite.  That are the only two options I see.  

I will check my email to see if I got a transfer notification. Cheers.

**Comment by AndyObtiva** [comment]
OK, I just accepted the invitation to cryptopunksnotdead.

**Comment by AndyObtiva** [comment]
Cool, I just saw the repo move to: https://github.com/cryptopunksnotdead/cryptopunks-gui

I was able to commit a 'development' branch to it, so I still have my rights in it.

Thank you.

**Comment by geraldb** [comment]
Fantastic. The repo is now @ https://github.com/cryptopunksnotdead/cryptopunks-gui

If you run into any issue with having no rights / access, please report.   I am not really an expert on github org access rights.     Welcome again and thanks for the fantastic addition. Keep it up. Cheers. Prost.

**Comment by AndyObtiva** [comment]
Yay! I got a new star on glimmer-dsl-libui from your posting today. Thank you.

**Comment by rubyFeedback** [comment]
> As you know I get labeled as a spammer and worse so not sure I am the right messanger :-).

You should not feel too discouraged about ad-hoc censorship. For instance I am censored on several reddit subs for
being hugely opinionated. Does that affect me? Not really. IMO it is better to ignore the censor-and-cancel movement
in general and just focus on where FACTS convince people: aka quality in software engineering. So, for instance,
in regards to the cyber-related stuff (including the GUI), showing nifty screenshots is a LOT better than wasting time
with the cancel-movement really. :)

(Andy writes excellent documentation. My all time favorite is still Jeremy in regards to sequel, but I have to say Andy 
is just about on par to it in regards to documentation/issues. Not sure whether it can be compared 1:1 because it
also depends on how many users there are, but quality-wise I think my statement about this being on par is quite
correct. I don't know all projects by Gerald so I can not evaluate; for instance I am not a real soccer fan so this is
already an area I will not really know much. But good software is useful either way, no matter the topic.)

**Comment by geraldb** [comment]
Yeah for sure - let's applaud (and thank) Andy for the outstanding documentation (and examples) on Glimmer. 

Unfortunately, you can no longer ignore ignore the censor-and-cancel movement but yeah for sure - don't let it consume all your time - speaking out from time to time and issueing a warning is the least one can do in an open society to safe guard democracy based on free sprech and tolerance and such.     Anyways, all the best. Cheers. Prost.

**Pull request merged**
