### PR TITLE
Day 11 - Adds boring generators

### LINKED ISSUE #35: Day 11 - BoringGenerators gem
Hey 👋 

I wrote a gem called boring generators which intents to generates the basic configurations and reduce the time taken in doing boring setup in a Rails application. The gem uses Rails generators. 

Here is short blog I wrote behind my motivation and problem I wanted to solve using the gem: https://www.abhaynikam.me/posts/introducing_boring_generators/

Hope this fit the requirement here. Please feel free to close the PR if it doesn't 😊 

GEM URL: https://github.com/abhaynikam/boring_generators

### PR DESCRIPTION
**Pull request by abhaynikam**
fixes #35

### CODE REVIEW

**Comment by geraldb** [comment]
Thanks for the boring generators write-up. Looks great. Cheers. Prost.

**Comment by geraldb** [comment]
FYI: Your boring_generators write-up is now live / published, see <https://planetruby.github.io/gems/2020/11-boring-generators>. Thanks again. Keep it up. Cheers. Prost.

**Comment by abhaynikam** [comment]
Thank you @geraldb 🎉 . Love the edits made in post ❤️

**Comment by geraldb** [comment]
Yeah, sorry for some small edits (I added your great generators line-up inline instead of linking to the readme) and moved the changelog to the resource section.   Thanks for the +1.  Keep it up. Great boring stuff.  Cheers. Prost.

**Pull request merged**
