### PR TITLE
Add draft about Blazer gem

### PR DESCRIPTION
**Pull request by marckohlbrugge**
Let me know if you have any feedback or requests for changes.

### CODE REVIEW

**Comment by swanson** [comment]
Looks great -- one comment: does this assume a Rails app? If so, might want to make a note about that as part of the installation.

**Comment by marckohlbrugge** [comment]
> Looks great -- one comment: does this assume a Rails app? If so, might want to make a note about that as part of the installation.

Done!

**Comment by swanson** [comment]
Thanks Marc, appreciate your help!

**Comment by geraldb** [comment]
Wow. What a gem of a write-up. Thanks. Danke. Cheers. Prost.

**Comment by geraldb** [comment]
FYI: Your write-up is now online / live <https://planetruby.github.io/gems/2020/03-blazer>. Thanks again. Cheers.

**Pull request merged**
