### PR TITLE
Day 22 - active-record-events

### PR DESCRIPTION
**Pull request by pienkowb**
Hi @geraldb, I've just finished the article about the [active_record-events](https://github.com/pienkowb/active_record-events) gem 🙂 I'll proofread it tomorrow, but it should be good to go. Please let me know if you have some comments or suggestions. Cheers!

### CODE REVIEW

**Comment by geraldb** [comment]
Sorry of not being of much help. Looks and reads great. Looking forward to publishing your active-record-events write-up. Thanks for taking the time. Cheers. Prost.

**Comment by pienkowb** [comment]
@geraldb I've double-checked the article – looks good to me :)

**Comment by geraldb** [comment]
Fantastic. Thanks again. Happy Holidays. Merry Christmas. Stay healthy. Cheers.

**Comment by pienkowb** [comment]
Hi @geraldb! Do you mind if I publish this article on other platforms (e.g. DEV, Medium)? It was a part of Ruby Advent Calendar 2020 and I want to make sure you're OK with that. Cheers!

**Comment by geraldb** [comment]
No need to ask - it's yours. Thanks for taking part in the advent calendar 2020! Prosit 2021! Please, do. Thanks, for sharing. Keep it up. Cheers.

**Comment by pienkowb** [comment]
Thanks! Cheers!

**Pull request merged**
