### PR TITLE
25 Days of Ruby Gems - local_time

### PR DESCRIPTION
**Pull request by swanson**
:wave:

Hey there! Neat project. I'd like to contribute a writeup on the `local_time` gem: https://github.com/basecamp/local_time

No preference on the day, so feel free to put it first, last, or anywhere in between :)

Wasn't exactly sure where to put the file, so let me know if you'd like me to move the file around or do anything other formatting tweaks.

### CODE REVIEW

**Comment by geraldb** [comment]
Wow. Thanks for the local_time gem article and thanks for supporting the ruby gems advent calenar.  No worries on where to put the file - the draft folder is great (other options are a gist or such).    

> No preference on the day, so feel free to put it first, last, or anywhere in between :)

Please, pick a day. If you are undecided you might try (in your ruby shell): 

    >> rand( 25 )+1 

and see what you get :-).  As a last resort I can run the script for you.    Again thanks for your contribution.

**Comment by swanson** [comment]
I'm happy to take Day 1 if it's open. Let's get the ball rolling :)

**Comment by geraldb** [comment]
Great. I merge your article / draft for now  and might slightly edit before launch to fit the format.  If you want to change anything later just let me know (or you are also welcome to join to github org so you can edit any time).  Again thanks for getting it all started. Greetings from Vienna, Austria. Cheers.

**Comment by swanson** [comment]
@geraldb Could you add me to the github org? I have a typo to fix and will be working on a few more posts.

**Comment by geraldb** [comment]
You are more than welcome. Check this org page here for the invite I am adding you right now - welcome.

**Pull request merged**
