### PR TITLE
Day 13 - Lumione

### PR DESCRIPTION
**Pull request by ledestin**
Hi,

It's a refined draft, I'm looking for feedback. 🙏 

I'm aware I need to update the title on the main page, but I'd like to refine the title first.

Thanks

### CODE REVIEW

**Comment by geraldb** [comment]
Looks and  reads great.  Fantastic to see a little paragraph on how use ActionView Helpers outside rails and on new opt plus gem.    I am Money gem newbie (maybe many others too?) - if it is not too much to ask, would be a great  if you can maybe add another paragraph with an example on how you use it with a currency or such.

About the title - do not worry really - usually as "editor / published" that's the only part (along with the bio)  I rewrite the title from the suggestion (for some consistency). 

Also no need to worry to update the readme itself - that is my chore every day.  
Thus, if it is still possible - add your write-up to the _drafts/ folder / dir - so I can merge (days before if you think you article is ready).
Again looks great / reads as is -  extra mile always welcome.  Keep it up. Cheers. Prost.

**Comment by geraldb** [comment]
Fantastic. Thanks for adding a paragraph / section on your money gem use. Reads great. Cheers. Prost.

**Comment by ledestin** [comment]
@geraldb thanks for the kind words.

I moved it to `_drafts`, and it's more or less ready. I'll have another read this week and update the PR as ready then.

**Comment by ledestin** [comment]
Thanks, it's ready to merge.

**Comment by geraldb** [comment]
Fantastic. Love it. Thanks for taking the time. Cheers. Prost.

**Comment by geraldb** [comment]
FYI: Wow. Great write-up now live / published on day 13 <https://planetruby.github.io/gems/2020/13-lumione>.   I add some section headlines and two extra lumione examples and moved the section up first. I hope you don't mind the (little) edits.  Again thanks for highlighting your gem and all the hand-selected gems / inside machinery .

**Pull request merged**
