### PR TITLE
Day 07 - letter_opener

### PR DESCRIPTION
**Pull request by swanson**

### CODE REVIEW

**Comment by geraldb** [comment]
Fantastic. Thanks for adding another post and claiming a free day! Let me know if the article is ready to merge.

Since you have two articles / post already - I am not sure if you are interested - you are of course more than welcome to join the planetruby (github) org than you can edit "inline" in the repo here as committer anytime - let me know and I send you the invite via github (github only works via invites)  Cheers. Prost.

**Comment by swanson** [comment]
@geraldb Yes, it is ready to merge. Yes, please invite, happy to help coordinate.

**Comment by geraldb** [comment]
Fantastic. Welcome. Thanks for claiming another day!

**Comment by swanson** [comment]
> Fantastic. Welcome. Thanks for claiming another day!

My pleasure. I've been trying to recruit some Ruby friends to submit today, so hopefully we can start filling up the days before December arrives :)

**Comment by geraldb** [comment]
Wow. Thanks again that would be a great help. All more than welcome. No worries - there's no deadline.    My backup plan was to fill-up unclaimed days with posts from the advent calendar 2017 <https://github.com/planetruby/calendar/tree/master/advent2017>  and if I get to it maybe some new ones.

**Pull request merged**
