### PR TITLE
Adds day 9 - gamesdb

### PR DESCRIPTION
**Pull request by picandocodigo**

### CODE REVIEW

**Comment by geraldb** [comment]
Big fan / supporter of open data. Thanks for the write-up on gamesdb. Keep it up. Looks / reads great. Cheers. Prost.

**Comment by picandocodigo** [comment]
Thanks @geraldb! I'm a big fan of Open Data myself, I've worked on quite a few Open Data related projects before and keep supporting it whenever I can :smile:

**Comment by geraldb** [comment]
Again looks / reads great.  As far as I can tell it is just missing a title / headline  and some links in the end for the reference sections. Keep up the great work. Cheers. Prost.

**Comment by geraldb** [comment]
Fantastic. Thanks again for taking the time. Great write-up. Cheers. Prost.

**Pull request merged**
