### PR TITLE
Day 20 - LHS and LHC

### LINKED ISSUE #24: Day 20 - Ruby Advent Calendar 2020 - LHS and LHC
Hey there 😊 

I came across the two gems [`LHS`](https://github.com/local-ch/lhs) and [`LHC`](https://github.com/local-ch/lhc) at a local Ruby Meetup pre-covid. I used them in a handful of projects since and really think they deserve more attention - because they are awesome and not well-known! Let me know if you think they fit in the Ruby Advent Calendar theme. 

Cheers, Marco

### PR DESCRIPTION
**Pull request by marcoroth**
Hey @geraldb, here's the article for Day 20 about LHS and LHC.

The article is finished content-wise. 
But I'm always open for any kind of feedback or suggestions!

Thank you!

Resolves #24.

### CODE REVIEW

**Comment by geraldb** [comment]
Sorry for the late reply.  Looks /reads great. Sorry of not being much help on the content.  I just edit / make the title a little longer and publish later today. Thanks again for the LHS and LHC write-up(s).  Cheers. Prost.

**Comment by geraldb** [comment]
FYI: Your LHS and LHC write-up is now live / published, see <https://planetruby.github.io/gems/2020/20-lhs-lhc>  Thanks again. Cheers. Prost.

**Comment by marcoroth** [comment]
Sure, no worries! 
Thanks for the review and the organization @geraldb 🙌

I wish you Happy Holidays and hope to see you around!
Cheers, Marco

**Comment by geraldb** [comment]
Thanks again. Happy Holidays. Merry Christmas. Prosit 2021! Cheers.

**Pull request merged**
