### PR TITLE
Fix product names

### PR DESCRIPTION
**Pull request by marckohlbrugge**

### CODE REVIEW

**Comment by swanson** [comment]
Sorry about that!

**Comment by marckohlbrugge** [comment]
> Sorry about that!

No worries. Thanks for the merge!

**Comment by geraldb** [comment]
Sorry I was trying to be clever by linking WIP to WIP  - on the WIP start / home page for newbies like myself it is hard to tell what WIP is about -  I only found the tagline "a community of makers shipping together" on the product page.  Again thanks for your great write-up. Cheers. Prost.

**Comment by marckohlbrugge** [comment]
> Sorry I was trying to be clever by linking WIP to WIP - on the WIP start / home page for newbies like myself it is hard to tell what WIP is about - I only found the tagline "a community of makers shipping together" on the product page. Again thanks for your great write-up. Cheers. Prost.

Thanks Gerald. That's actually a great point. I should clarify the homepage.

**Comment by geraldb** [comment]
No worries. WIP is a great idea by the way and amazing what you have built. Happy holiday season. Cheers. Prost.

**Pull request merged**
